# AUTOGENERATED FROM 'app/queries/add_file.edgeql' WITH:
#     $ edgedb-py -I hackathon --tls-security insecure --skip-pydantic-validation


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class AddFileResult(NoPydanticValidation):
    id: uuid.UUID


async def add_file(
    executor: edgedb.AsyncIOExecutor,
    *,
    user_id: uuid.UUID,
    origin_filename: str,
    obj_key: str | None,
) -> AddFileResult:
    return await executor.query_single(
        """\
        insert File {
          owner := (
            select User
            filter .id = <uuid>$user_id
          ),
          origin_filename := <str>$origin_filename,
          obj_key := <optional str>$obj_key
        }\
        """,
        user_id=user_id,
        origin_filename=origin_filename,
        obj_key=obj_key,
    )
