# AUTOGENERATED FROM 'app/queries/add_file.edgeql' WITH:
#     $ edgedb-py --skip-pydantic-validation


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass

        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class AddFileResult(NoPydanticValidation):
    id: uuid.UUID


async def add_file(
    executor: edgedb.AsyncIOExecutor,
    *,
    user_id: uuid.UUID,
) -> AddFileResult:
    return await executor.query_single(
        """\
        insert File {
          owner := (
            select User
            filter .id = <uuid>$user_id
          )
        }\
        """,
        user_id=user_id,
    )
