# AUTOGENERATED FROM 'app/queries/add_token.edgeql' WITH:
#     $ edgedb-py --dsn edgedb://edgedb@localhost --tls-security insecure --skip-pydantic-validation


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class AddTokenResult(NoPydanticValidation):
    id: uuid.UUID


async def add_token(
    executor: edgedb.AsyncIOExecutor,
    *,
    user_id: uuid.UUID,
    token: str,
) -> AddTokenResult:
    return await executor.query_single(
        """\
        insert Token {
          owner := (
            select User
            filter .id = <uuid>$user_id
          ),
          value := <str>$token
        }\
        """,
        user_id=user_id,
        token=token,
    )
