# AUTOGENERATED FROM 'app/queries/delete_token.edgeql' WITH:
#     $ edgedb-py --skip-pydantic-validation


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass

        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class DeleteTokenResult(NoPydanticValidation):
    id: uuid.UUID


async def delete_token(
    executor: edgedb.AsyncIOExecutor,
    *,
    token: str,
) -> DeleteTokenResult | None:
    return await executor.query_single(
        """\
        delete Token filter .value = <str>$token\
        """,
        token=token,
    )
