# AUTOGENERATED FROM 'app/queries/get_user_by_token.edgeql' WITH:
#     $ edgedb-py --skip-pydantic-validation


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass

        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetUserByTokenResult(NoPydanticValidation):
    id: uuid.UUID
    token: str


async def get_user_by_token(
    executor: edgedb.AsyncIOExecutor,
    *,
    token: str,
) -> GetUserByTokenResult | None:
    return await executor.query_single(
        """\
        select User {id, token := <str>$token} filter .tokens.value = <str>$token limit 1\
        """,
        token=token,
    )
