# AUTOGENERATED FROM 'app/queries/get_tasks.edgeql' WITH:
#     $ edgedb-py -I hackathon --tls-security insecure --skip-pydantic-validation


from __future__ import annotations
import dataclasses
import datetime
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass

        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetTasksResult(NoPydanticValidation):
    id: uuid.UUID
    name: str
    code: str
    predicted_end_date: datetime.datetime | None
    actual_end_date: datetime.datetime | None
    reasons: list[GetTasksResultReasonsItem]


@dataclasses.dataclass
class GetTasksResultReasonsItem(NoPydanticValidation):
    id: uuid.UUID
    name: str
    about: str


async def get_tasks(
    executor: edgedb.AsyncIOExecutor,
    *,
    subject_id: uuid.UUID,
) -> list[GetTasksResult]:
    return await executor.query(
        """\
        select Task {
          name,
          code,
          predicted_end_date,
          actual_end_date,
          reasons: {
            name,
            about
          }
        }
        filter .subject.id = <uuid>$subject_id\
        """,
        subject_id=subject_id,
    )
